server:
  port: 8092    
spring:     #定义springmvc视图解析器
  mvc:    view:      prefix: /WEB-INF/views/
      suffix: .jsp

dubbo:  application:    name: consumer-user  scan:    base-packages: com.jt  registry:    address: zookeeper://192.168.193.4:2181?backup=192.168.193.4:2182,192.168.193.4:2183
            #zookeeper://192.168.193.4:2181?backup=192.168.193.4:2182,192.168.193.4:2183
 